#!/bin/sh
# @(#)UNINSTALL-jai_imageio	6.2 04/11/09
# usage: UNINSTALL-jai_imageio

echo "Uninstalling Java Advanced Imaging Image I/O Tools"

rm -f *jai_imageio.txt
rm -f lib/jai_imageio.jar
rm -f lib/clibwrapper_jiio.jar
rm -f lib/libclib_jiio.so
if [ \( `uname` = "SunOS" \) -a \( `uname -p` = "sparc" \) ]; then
    rm -f lib/cpu/sparcv9+vis/sparcv9/libclib_jiio.so
    rmdir lib/cpu/sparcv9+vis/sparcv9
    rm -f lib/cpu/sparcv9+vis/libclib_jiio.so
    rmdir lib/cpu/sparcv9+vis
    rm -f lib/cpu/sparcv9+vis2/sparcv9/libclib_jiio.so
    rmdir lib/cpu/sparcv9+vis2/sparcv9
    rm -f lib/cpu/sparcv9+vis2/libclib_jiio.so
    rmdir lib/cpu/sparcv9+vis2/
    rmdir lib/cpu
    rm -f lib/sparcv9/libclib_jiio.so
    rmdir lib/sparcv9
fi
rmdir lib
rm -f UNINSTALL-jai_imageio

echo "Done"
